_format_version: '3.0'
_transform: true

services:
  - name: first-demo
    url: https://httpbin.org/anything
    routes:
      - name: first-demo-route
        paths:
          - /test

plugins:
  - config:
      message: hello from kong Go plugin
    enabled: true
    name: kongo
# curl -XPOST http://10.128.3.68:8001/plugins -H "Content-Type: application/json" \
# --data '{"enabled":false,"name":"kongo"}'
