version: '3.8'
services:
  kong:
    # image: kong/kong-gateway:3.4.2.0
    platform: linux/x86_64
    image: xpop/kongo:3.4.2.12
    build:
      context: .
      dockerfile: Dockerfile
    # command: ['tail', '-f']
    # volumes:
    #   - ./kongo:/usr/local/bin/kongo
    env_file:
      - .env
    ports:
      - '8000-8004:8000-8004'
